name: main

on:
  workflow_dispatch:
    inputs:
      package-version:
        type: string
        description: Package version
        required: false
      deploy:
        type: boolean
        description: Deploy package
        required: false
        default: false
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Build YoutubeExplode
        run: |
          dotnet build -c Release

      - name: Install ILLLLVM
        run: |
          # Install ILLLLVM to convert IL to LLVM IR
          sudo apt-get install -y llvm clang
          git clone https://github.com/llilc/illlvm.git
          cd illlvm
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Convert C# DLL to LLVM IR
        run: |
          # Convert the compiled YoutubeExplode DLL to LLVM IR
          illlvm YourLibrary.dll -o YoutubeExplode.ll

      - name: Compile LLVM IR to Native Library
        run: |
          # Compile the LLVM IR to a shared library for Android
          clang -shared -o libyoutubeexplode.so YoutubeExplode.ll -target armv7-none-linux-androideabi

      - name: Upload Native Library
        uses: actions/upload-artifact@v2
        with:
          name: libyoutubeexplode
          path: libyoutubeexplode.so

  deploy:
    needs: build
    uses: Tyrrrz/.github/.github/workflows/nuget.yml@master
    with:
      skip-tests: true
      deploy: ${{ inputs.deploy || github.ref_type == 'tag' }}
      package-version: ${{ inputs.package-version || (github.ref_type == 'tag' && github.ref_name) || format('0.0.0-ci-{0}', github.sha) }}
      dotnet-version: 8.0.x
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
